### PR TITLE
+korean text

### PR DESCRIPTION
**Pull request by sikanderiqbal**
YES = 네
NO = 아니요

### CODE REVIEW

**Comment by sikanderiqbal** [comment]
I'll re-do this translation + pull-request

**Comment by konklone** [comment]
@sikanderiqbal would you mind reopening? I'd like to use the merge conflict resolver.

**Comment by konklone** [comment]
I already tweeted about it and everything. ;) https://twitter.com/konklone/status/808170424404209664

**Comment by sikanderiqbal** [comment]
Oh no.. GitHub is not letting me re-open :(

**Comment by konklone** [comment]
Oh well! I'll look forward to the next merge conflict. ;)

**Pull request closed without merging**
